[project]
name = "github-wiki-see-rs-sitemaps"
version = "0.1.0"
description = ""
requires-python = ">=3.9"
dependencies = [
    "google-cloud-bigquery>=2.18.0",
    "tqdm>=4.61.0",
    "smart-open>=5.1.0",
    "diskcache>=5.4.0",
]

[project.optional-dependencies]
dev = [
    "google-cloud-pubsub>=2.5.0",
]
