name: Build and Ping
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  build_and_ping:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: github-wiki-see
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Cache Processed Results
        id: cache-results
        uses: actions/cache@v3
        with:
          path: generator/cache
          key: ccache-${{ github.run_id }}
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}-${{ steps.setup-python.outputs.python-version }}
      - run: poetry install
      - run: poetry run python generate.py --hours_back=365
        working-directory: ./generator
        env:
          PYTHONUNBUFFERED: 1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
      - uses: atymic/sitemap-ping-action@1.0.0
        with:
          sitemap-url: https://github-wiki-see.page/generated_sitemap.xml
